name: svcphone
version: '0.1'
main: fr.vasolix.svcphone.SimplePhoneCallPlugin
api-version: '1.21'
libraries:
  - org.jetbrains.kotlin:kotlin-maven-plugin:2.1.20-RC
commands:
  call:
    description: Permet d'appeler
    usage: /call <playername>
  answer:
    description: Répondre à un appel entrant.
    usage: /answer
  decline:
    description: Refuser un appel entrant.
    usage: /decline
  hangup:
    description: Raccrocher un appel en cours.
    usage: /hangup
  block:
    description: Permet de bloquer des personnes.
    usage: /block <playername>
  unblock:
    description: Permet de débloquer des personnes.
    usage: /unblock <playername>
  blocklist:
    description: Affiche la liste des personnes bloquées.
    usage: /blocklist

depend: [voicechat]
